# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  ssl_certificate: /etc/ssl/fullchain.cer
  ssl_key: /etc/ssl/app.dipuce.com.key
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.100.1.201