services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/docker/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      pub_net:
        ipv4_address: 10.100.1.201
    hostname: app.home.dipuce.com
volumes:
  caddy_data:
  caddy_config:
networks:
  pub_net:
    external: true