version: '3'
services:
  homeassistant:
    container_name: homeassistant
    hostname: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /certs/app.dipuce.com:/etc/user-ssl
    restart: unless-stopped
    privileged: true
    networks:
      pub_net:
        ipv4_address: 10.100.1.203
networks:
  pub_net:
    external: true