version: '3'
services:
  homeassistant:
    container_name: homeassistant
    hostname: ha
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      pub_net:
        ipv4_address: 10.100.1.203
networks:
  pub_net:
    external: true