version: '3'
services:
  hyperion:
    container_name: hyperion_ng
    hostname: hyperion
    image: sirfragalot/hyperion.ng:2.0.0-alpha.9-x86_64
    volumes:
      - /home/docker/hyperion:/root/.hyperion:rw
    restart: unless-stopped
    networks:
      pub_net:
        ipv4_address: 10.100.1.205
networks:
  pub_net:
    external: true