services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=n8n.app.dipuce.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.app.dipuce.com/
      - GENERIC_TIMEZONE=America/New_York
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/docker/n8n/local-files:/files
    networks:
      pub_net:
        ipv4_address: 10.100.1.208

volumes:
  n8n_data:
  traefik_data:
networks:
  pub_net:
    external: true