services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=3007
      - PGID=3007
      - TZ=America/New_York
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=10.100.1.218
      - APACHE_ADDITIONAL_NETWORK=""
      - SKIP_DOMAIN_VALIDATION=false
      - AIO_COMMUNITY_CONTAINERS="local-ai memories"
    volumes:
      - ./config:/config
      - /mnt/cloud:/data
    networks:
      pub_net:
        ipv4_address: 10.100.1.218
    ports:
      - "8080:8080"
      - "11000:11000"
    restart: unless-stopped

networks:
  pub_net:
    external: true