version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=$PLEX_CLAIM
    networks:
      pub_net:
        ipv4_address: 10.100.1.207
    hostname: plex.home.dipuce.com
    volumes:
      - /home/docker/plexms/config:/config
      - /home/docker/plexms/transcodes:/transcode
      - g_media2:/data
networks:
  pub_net:
    external: true
volumes:
  g_media2:
    external: true